### ISSUE TITLE
OpModes do not exist

### ISSUE THREAD

**Issue by WardBenjamin** [OliviliK/FTC_Library#1]
Hey Olivili,

Just wanted to let you know that the repository that you said that your opmodes were in (in your README) is either not public or does not exist.

Thanks for all of the work you've done on the Wire library! I've used it for a lot more interesting things than just sensors, and I'll be posting about it and maybe releasing code after our first competition in early December.

Thanks,
Benjamin Ward
Programming Lead, FTC 4592

**Comment by OliviliK** [comment]
Ben,

I got derailed from the FTC activities due to the release of Fallout 4 on 11/11.  Now I have spend 3 days (72 hours) playing that game.  Perhaps during this week end, I will start the OpModes repository.

Cheers, Ollie

**Comment by WardBenjamin** [comment]
Thanks Ollie,

I personally don't need the Op Modes, so no rush. It'd be nice for rookie teams though!

Benjamin Ward
